# NOTE::
#
# The services, settings and environment setup in this compose file is
# for DEVELOPMENT ONLY!
#
# Do not use this compose file in a live environment.

services:
  db:
    image: mysql:8.4
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      # Automatically populate timezones on first boot
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      # This loads timezone data into the MySQL container
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ucnrs_rams_development

  web:
    build: .
    command: bash -c 'rm -f tmp/pids/server.pid && bundle exec rails s --port 3000 --binding 0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 3000:3000
    # These override your local .env values ONLY inside the container
    environment:
      - DATABASE_NAME=unnrs_rams_development
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=password
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
    depends_on:
      - db

volumes:
    db_data:
