development:
  adapter: solid_cable
  polling_interval: 0.3.seconds
  message_retention: 1.day

test:
  adapter: test

dev_server:
  adapter: solid_cable
  polling_interval: 0.3.seconds
  message_retention: 1.day

production:
  adapter: solid_cable
  polling_interval: 0.3.seconds
  message_retention: 1.day
