default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_0900_ai_ci
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] && ENV['OVERRIDE_DB_NAME'] == 'true' ? ENV['DATABASE_NAME'] : 'ucnrs_rams_development' %>

dev_server:
  <<: *default
  # use the database passed in as ENV Variable and don't override it.
  # No reason to change this on servers which should give correct name (really no need to change it at all when
  # the databases are on different hosts)

staging:
  <<: *default
  # use the database passed in as ENV Variable and don't override it.

test:
  <<: *default
  database: ucnrs_rams_test

production:
  <<: *default
