# frozen_string_literal: true

require 'rails_helper'

# Configures the OpenAPI document generated by the specs in spec/api.
# Run `bundle exec rake rswag:specs:swaggerize` to regenerate
# swagger/v1/swagger.yaml after changing the API or these specs.
RSpec.configure do |config|
  config.openapi_root = Rails.root.join('swagger').to_s

  config.openapi_specs = {
    'v1/swagger.yaml' => {
      openapi: '3.0.1',
      info: {
        title: 'RAMS API',
        version: 'v1',
        description: <<~DESCRIPTION,
          Read-only JSON API for UC Natural Reserve System research projects.

          All endpoints require a Bearer token issued to an `ApiClient`. A client
          may be scoped to a single reserve; scoping only narrows what a client
          can read. See `docs/api.md` for how to create and rotate clients.
        DESCRIPTION
        license: {
          name: 'MIT',
          url: 'https://github.com/UCNRS-RAMS/ucnrs-rams/blob/main/LICENSE.md'
        }
      },
      paths: {},
      servers: [
        {
          # Relative to the host serving this document, so the same spec works
          # in every environment.
          url: '/'
        }
      ],
      security: [{ bearerAuth: [] }],
      tags: [
        {
          name: 'Projects',
          description: 'Research, class, meeting, public use, and housing projects.'
        }
      ],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: :http,
            scheme: :bearer,
            description: <<~DESCRIPTION.strip
              Requests must send `Authorization: Bearer <token>`, where `<token>`
              is an `ApiClient` token. In Swagger UI, click Authorize and paste
              the token without the `Bearer ` prefix. Tokens are shown once when
              a client is created or rotated, for example with
              `bin/rails api:clients:create NAME="My integration"`.
            DESCRIPTION
          }
        },
        schemas: {
          Project: {
            type: :object,
            required: %w[id type title status project_type],
            properties: {
              id: { type: :integer },
              type: { type: :string, enum: ['projects'] },
              title: { type: :string, nullable: true },
              status: {
                type: :string,
                enum: Project.statuses.keys,
                description: 'Rails enum key.'
              },
              project_type: {
                type: :string,
                enum: Project.project_types.keys,
                description: 'Rails enum key.'
              },
              abstract: { type: :string, nullable: true },
              discipline: { type: :string, nullable: true },
              discipline_other: { type: :string, nullable: true },
              keywords: { type: :string, nullable: true },
              taxonomic_keywords: { type: :string, nullable: true },
              thesis_title: { type: :string, nullable: true },
              course_title: { type: :string, nullable: true },
              course_number: { type: :string, nullable: true },
              start_date: { type: :string, format: :date, nullable: true },
              end_date: { type: :string, format: :date, nullable: true },
              submitted_at: { type: :string, format: 'date-time', nullable: true },
              reserve: {
                type: :object,
                nullable: true,
                allOf: [{ '$ref' => '#/components/schemas/ReserveStub' }]
              },
              owner: {
                type: :object,
                nullable: true,
                allOf: [{ '$ref' => '#/components/schemas/UserStub' }]
              },
              applicant: {
                type: :object,
                nullable: true,
                allOf: [{ '$ref' => '#/components/schemas/UserStub' }]
              },
              created_at: { type: :string, format: 'date-time' },
              updated_at: { type: :string, format: 'date-time' }
            }
          },
          ReserveStub: {
            type: :object,
            required: %w[type id name short_name],
            properties: {
              type: { type: :string, enum: ['reserves'] },
              id: { type: :integer },
              name: { type: :string },
              short_name: { type: :string, nullable: true }
            }
          },
          UserStub: {
            type: :object,
            required: %w[type id full_name orcid],
            properties: {
              type: { type: :string, enum: ['users'] },
              id: { type: :integer },
              full_name: { type: :string },
              orcid: { type: :string, nullable: true }
            }
          },
          ProjectsCollection: {
            type: :object,
            required: %w[data meta],
            properties: {
              data: {
                type: :array,
                items: { '$ref' => '#/components/schemas/Project' }
              },
              meta: { '$ref' => '#/components/schemas/PaginationMeta' }
            }
          },
          ProjectResource: {
            type: :object,
            required: %w[data],
            properties: {
              data: { '$ref' => '#/components/schemas/Project' }
            }
          },
          PaginationMeta: {
            type: :object,
            required: %w[page per_page total_pages total_count],
            properties: {
              page: { type: :integer },
              per_page: { type: :integer },
              total_pages: { type: :integer },
              total_count: { type: :integer }
            }
          },
          Error: {
            type: :object,
            required: %w[error],
            properties: {
              error: {
                type: :string,
                enum: %w[unauthorized not_found bad_request]
              },
              detail: {
                type: :string,
                nullable: true,
                description: 'Present on 400 responses, explaining the rejected value.'
              }
            }
          }
        }
      }
    }
  }

  config.openapi_format = :yaml
end
