# frozen_string_literal: true

require 'rails_helper'

# Configures the OpenAPI document generated by the specs in spec/api.
# Run `bundle exec rake rswag:specs:swaggerize` to regenerate
# swagger/v1/swagger.yaml after changing the API or these specs.
#
# Endpoint-specific metadata (tags, schemas, parameters) lives with the specs;
# this file only holds document-wide configuration shared by every version.
RSpec.configure do |config|
  config.openapi_root = Rails.root.join('swagger').to_s

  config.openapi_specs = {
    'v1/swagger.yaml' => {
      openapi: '3.0.1',
      info: {
        title: 'RAMS API',
        version: 'v1',
        description: <<~DESCRIPTION,
          Read-only JSON API for UC Natural Reserve System research projects.

          All endpoints require a Bearer token issued to an `ApiClient`. A client
          may be scoped to a single reserve; scoping only narrows what a client
          can read. See `docs/api.md` for how to create and rotate clients.
        DESCRIPTION
        license: {
          name: 'MIT',
          url: 'https://github.com/UCNRS-RAMS/ucnrs-rams/blob/main/LICENSE.md'
        }
      },
      paths: {},
      servers: [
        {
          # Relative to the host serving this document, so the same spec works
          # in every environment.
          url: '/'
        }
      ],
      security: [{ bearerAuth: [] }],
      components: {
        securitySchemes: {
          bearerAuth: {
            type: :http,
            scheme: :bearer,
            description: <<~DESCRIPTION.strip
              Requests must send `Authorization: Bearer <token>`, where `<token>`
              is an `ApiClient` token. In Swagger UI, click Authorize and paste
              the token without the `Bearer ` prefix. Tokens are shown once when
              a client is created or rotated, for example with
              `bin/rails api:clients:create NAME="My integration"`.
            DESCRIPTION
          }
        }
      }
    }
  }

  config.openapi_format = :yaml
end
