class PopulateReserveTags < ActiveRecord::Migration[6.1]
  def up
    time_current = Time.current.to_s(:db)

    execute(<<-end_sql)
    INSERT INTO `reserve_tags` (`id`, `reserve_id`, `category`, `name`, `created_at`, `updated_at`) VALUES
    (1, 29, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (2, 29, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (3, 29, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (4, 29, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (5, 29, 'ecosystem', 'River', '#{time_current}', '#{time_current}'),
    (6, 29, 'ecosystem', 'Riparian', '#{time_current}', '#{time_current}'),
    (7, 29, 'ecosystem', 'Mountains', '#{time_current}', '#{time_current}'),
    (8, 29, 'geographic', 'Northern California', '#{time_current}', '#{time_current}'),
    (9, 29, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (10, 29, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (11, 29, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (12, 29, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (13, 29, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (14, 29, 'amenities', 'Vehicle', '#{time_current}', '#{time_current}'),
    (15, 29, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (16, 29, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (17, 29, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (18, 29, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (19, 29, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (20, 9, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (21, 9, 'ecosystem', 'Costal Marine', '#{time_current}', '#{time_current}'),
    (22, 9, 'ecosystem', 'Coastal Prairie', '#{time_current}', '#{time_current}'),
    (23, 9, 'geographic', 'Coastal', '#{time_current}', '#{time_current}'),
    (24, 9, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (25, 9, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (26, 9, 'facility', 'No Facilities', '#{time_current}', '#{time_current}'),
    (27, 9, 'internet', 'Cell Phone Only', '#{time_current}', '#{time_current}'),
    (28, 9, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (29, 9, 'amenities', 'Boat', '#{time_current}', '#{time_current}'),
    (30, 35, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (31, 35, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (32, 35, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (33, 35, 'ecosystem', 'Serpentine', '#{time_current}', '#{time_current}'),
    (34, 35, 'ecosystem', 'Riparian', '#{time_current}', '#{time_current}'),
    (35, 35, 'ecosystem', 'River', '#{time_current}', '#{time_current}'),
    (36, 35, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (37, 35, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (38, 35, 'geographic', 'Coast Range', '#{time_current}', '#{time_current}'),
    (39, 35, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (40, 35, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (41, 35, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (42, 35, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (43, 35, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (44, 35, 'amenities', 'Vehicle', '#{time_current}', '#{time_current}'),
    (45, 35, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (46, 35, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (47, 35, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (48, 35, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (49, 35, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (50, 35, 'amenities', 'RV hook-ups', '#{time_current}', '#{time_current}'),
    (51, 11, 'ecosystem', 'Costal Marine', '#{time_current}', '#{time_current}'),
    (52, 11, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (53, 11, 'ecosystem', 'Marsh', '#{time_current}', '#{time_current}'),
    (54, 11, 'ecosystem', 'Dunes', '#{time_current}', '#{time_current}'),
    (55, 11, 'ecosystem', 'Rocky Intertidal', '#{time_current}', '#{time_current}'),
    (56, 11, 'ecosystem', 'Beach', '#{time_current}', '#{time_current}'),
    (57, 11, 'geographic', 'Coastal', '#{time_current}', '#{time_current}'),
    (58, 11, 'geographic', 'Northern California', '#{time_current}', '#{time_current}'),
    (59, 11, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (60, 11, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (61, 11, 'internet', 'Broadband Internet', '#{time_current}', '#{time_current}'),
    (62, 11, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (63, 11, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (64, 11, 'amenities', 'Vehicle', '#{time_current}', '#{time_current}'),
    (65, 11, 'amenities', 'Boat', '#{time_current}', '#{time_current}'),
    (66, 11, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (67, 11, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (68, 11, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (69, 11, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (70, 11, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (71, 11, 'amenities', 'Animal care facilities', '#{time_current}', '#{time_current}'),
    (72, 11, 'amenities', 'Library', '#{time_current}', '#{time_current}'),
    (73, 11, 'amenities', 'Wet Lab', '#{time_current}', '#{time_current}'),
    (74, 11, 'amenities', 'Greenhouse', '#{time_current}', '#{time_current}'),
    (75, 11, 'amenities', 'Marine Operations', '#{time_current}', '#{time_current}'),
    (76, 1, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (77, 1, 'ecosystem', 'Coastal Sage Scrub', '#{time_current}', '#{time_current}'),
    (78, 1, 'geographic', 'Southern California', '#{time_current}', '#{time_current}'),
    (79, 1, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (80, 1, 'facility', 'No Facilities', '#{time_current}', '#{time_current}'),
    (81, 1, 'internet', 'No Network', '#{time_current}', '#{time_current}'),
    (82, 5, 'ecosystem', 'Desert', '#{time_current}', '#{time_current}'),
    (83, 5, 'ecosystem', 'Piñon-Juniper Woodland', '#{time_current}', '#{time_current}'),
    (84, 5, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (85, 5, 'geographic', 'Desert', '#{time_current}', '#{time_current}'),
    (86, 5, 'geographic', 'Southern California', '#{time_current}', '#{time_current}'),
    (87, 5, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (88, 5, 'facility', 'Accommodate Less Than 30 Overnight', '#{time_current}', '#{time_current}'),
    (89, 5, 'internet', 'Broadband Internet', '#{time_current}', '#{time_current}'),
    (90, 5, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (91, 5, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (92, 5, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (93, 5, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (94, 5, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (95, 5, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (96, 5, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (97, 20, 'ecosystem', 'Costal Marine', '#{time_current}', '#{time_current}'),
    (98, 20, 'ecosystem', 'Marsh', '#{time_current}', '#{time_current}'),
    (99, 20, 'ecosystem', 'Estuary', '#{time_current}', '#{time_current}'),
    (100, 20, 'geographic', 'Coastal', '#{time_current}', '#{time_current}'),
    (101, 20, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (102, 20, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (103, 20, 'facility', 'No Facilities', '#{time_current}', '#{time_current}'),
    (104, 20, 'internet', 'No Network', '#{time_current}', '#{time_current}'),
    (105, 20, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (106, 18, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (107, 18, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (108, 18, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (109, 18, 'geographic', 'Northern California', '#{time_current}', '#{time_current}'),
    (110, 18, 'geographic', 'Sierra Nevada', '#{time_current}', '#{time_current}'),
    (111, 18, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (112, 18, 'facility', 'No Facilities', '#{time_current}', '#{time_current}'),
    (113, 18, 'internet', 'No Network', '#{time_current}', '#{time_current}'),
    (114, 18, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (115, 12, 'ecosystem', 'Costal Marine', '#{time_current}', '#{time_current}'),
    (116, 12, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (117, 12, 'ecosystem', 'Marsh', '#{time_current}', '#{time_current}'),
    (118, 12, 'ecosystem', 'Vernal Pools', '#{time_current}', '#{time_current}'),
    (119, 12, 'ecosystem', 'Coastal Sage Scrub', '#{time_current}', '#{time_current}'),
    (120, 12, 'ecosystem', 'Dune', '#{time_current}', '#{time_current}'),
    (121, 12, 'geographic', 'Coastal', '#{time_current}', '#{time_current}'),
    (122, 12, 'geographic', 'Southern California', '#{time_current}', '#{time_current}'),
    (123, 12, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (124, 12, 'facility', 'Lab facility Only', '#{time_current}', '#{time_current}'),
    (125, 12, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (126, 12, 'amenities', 'Vehicle', '#{time_current}', '#{time_current}'),
    (127, 12, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (128, 12, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (129, 12, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (130, 12, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (131, 12, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (132, 100011, 'ecosystem', 'Desert', '#{time_current}', '#{time_current}'),
    (133, 100011, 'ecosystem', 'Alkali wetlands', '#{time_current}', '#{time_current}'),
    (134, 100011, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (135, 100011, 'geographic', 'Desert', '#{time_current}', '#{time_current}'),
    (136, 100011, 'geographic', 'Southern California', '#{time_current}', '#{time_current}'),
    (137, 100011, 'geographic', 'Eastern California', '#{time_current}', '#{time_current}'),
    (138, 100011, 'organization', 'CSU', '#{time_current}', '#{time_current}'),
    (139, 100011, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (140, 100011, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (141, 100011, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (142, 100011, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (143, 100011, 'amenities', 'Boat', '#{time_current}', '#{time_current}'),
    (144, 100011, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (145, 100011, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (146, 100011, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (147, 100011, 'amenities', 'Library', '#{time_current}', '#{time_current}'),
    (148, 100011, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (149, 26, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (150, 26, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (151, 26, 'ecosystem', 'Coastal Sage Scrub', '#{time_current}', '#{time_current}'),
    (152, 26, 'geographic', 'Southern California', '#{time_current}', '#{time_current}'),
    (153, 26, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (154, 26, 'facility', 'No Facilities', '#{time_current}', '#{time_current}'),
    (155, 26, 'internet', 'No Network', '#{time_current}', '#{time_current}'),
    (156, 26, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (157, 31, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (158, 31, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (159, 31, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (160, 31, 'ecosystem', 'Coastal Sage Scrub', '#{time_current}', '#{time_current}'),
    (161, 31, 'ecosystem', 'Dune', '#{time_current}', '#{time_current}'),
    (162, 31, 'geographic', 'Coastal', '#{time_current}', '#{time_current}'),
    (163, 31, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (164, 31, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (165, 31, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (166, 31, 'internet', 'Cell Phone Only', '#{time_current}', '#{time_current}'),
    (167, 31, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (168, 31, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (169, 31, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (170, 3, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (171, 3, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (172, 3, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (173, 3, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (174, 3, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (175, 3, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (176, 3, 'internet', 'Broadband Internet', '#{time_current}', '#{time_current}'),
    (177, 3, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (178, 3, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (179, 3, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (180, 3, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (181, 3, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (182, 3, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (183, 3, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (184, 3, 'amenities', 'Library', '#{time_current}', '#{time_current}'),
    (185, 100009, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (186, 100009, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (187, 100009, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (188, 100009, 'ecosystem', 'Vernal Pools', '#{time_current}', '#{time_current}'),
    (189, 100009, 'geographic', 'Coastal', '#{time_current}', '#{time_current}'),
    (190, 100009, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (191, 100009, 'geographic', 'Northern California', '#{time_current}', '#{time_current}'),
    (192, 100009, 'organization', 'UC ANR', '#{time_current}', '#{time_current}'),
    (193, 100009, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (194, 100009, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (195, 100009, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (196, 100009, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (197, 100009, 'amenities', 'Vehicle', '#{time_current}', '#{time_current}'),
    (198, 100009, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (199, 100009, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (200, 100009, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (201, 100009, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (202, 100009, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (203, 100009, 'amenities', 'Animal care facilities', '#{time_current}', '#{time_current}'),
    (204, 7, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (205, 7, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (206, 7, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (207, 7, 'geographic', 'Southern California', '#{time_current}', '#{time_current}'),
    (208, 7, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (209, 7, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (210, 7, 'internet', 'DSL Internet', '#{time_current}', '#{time_current}'),
    (211, 7, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (212, 7, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (213, 7, 'amenities', 'Vehicle', '#{time_current}', '#{time_current}'),
    (214, 7, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (215, 7, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (216, 7, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (217, 7, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (218, 7, 'amenities', 'Library', '#{time_current}', '#{time_current}'),
    (219, 24, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (220, 24, 'ecosystem', 'Marsh', '#{time_current}', '#{time_current}'),
    (221, 24, 'ecosystem', 'Vernal Pools', '#{time_current}', '#{time_current}'),
    (222, 24, 'geographic', 'Central Valley', '#{time_current}', '#{time_current}'),
    (223, 24, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (224, 24, 'facility', 'No Facilities', '#{time_current}', '#{time_current}'),
    (225, 24, 'internet', 'No Network', '#{time_current}', '#{time_current}'),
    (226, 33, 'ecosystem', 'Costal Marine', '#{time_current}', '#{time_current}'),
    (227, 33, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (228, 33, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (229, 33, 'ecosystem', 'Coastal Sage Scrub', '#{time_current}', '#{time_current}'),
    (230, 33, 'ecosystem', 'Rocky intertidal zone', '#{time_current}', '#{time_current}'),
    (231, 33, 'ecosystem', 'Beach', '#{time_current}', '#{time_current}'),
    (232, 33, 'geographic', 'Coastal', '#{time_current}', '#{time_current}'),
    (233, 33, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (234, 33, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (235, 33, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (236, 33, 'internet', 'Cable Internet', '#{time_current}', '#{time_current}'),
    (237, 33, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (238, 33, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (239, 33, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (240, 33, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (241, 33, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (242, 33, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (243, 22, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (244, 22, 'ecosystem', 'Costal Marine', '#{time_current}', '#{time_current}'),
    (245, 22, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (246, 22, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (247, 22, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (248, 22, 'ecosystem', 'Coastal Sage Scrub', '#{time_current}', '#{time_current}'),
    (249, 22, 'ecosystem', 'Redwoods', '#{time_current}', '#{time_current}'),
    (250, 22, 'ecosystem', 'Serpentine', '#{time_current}', '#{time_current}'),
    (251, 22, 'geographic', 'Coastal', '#{time_current}', '#{time_current}'),
    (252, 22, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (253, 22, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (254, 22, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (255, 22, 'internet', 'Satellite Internet', '#{time_current}', '#{time_current}'),
    (256, 22, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (257, 22, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (258, 22, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (259, 22, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (260, 22, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (261, 41, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (262, 41, 'ecosystem', 'Montane', '#{time_current}', '#{time_current}'),
    (263, 41, 'ecosystem', 'Alpine', '#{time_current}', '#{time_current}'),
    (264, 41, 'ecosystem', 'Hydrothermal', '#{time_current}', '#{time_current}'),
    (265, 41, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (266, 41, 'geographic', 'Northern California', '#{time_current}', '#{time_current}'),
    (267, 41, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (268, 41, 'facility', 'Accommodate Less Than 30 Overnight', '#{time_current}', '#{time_current}'),
    (269, 41, 'internet', 'Cell Phone Only', '#{time_current}', '#{time_current}'),
    (270, 41, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (271, 41, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (272, 28, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (273, 28, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (274, 28, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (275, 28, 'ecosystem', 'Vernal Pools', '#{time_current}', '#{time_current}'),
    (276, 28, 'ecosystem', 'Serpentine', '#{time_current}', '#{time_current}'),
    (277, 28, 'ecosystem', 'Meadow', '#{time_current}', '#{time_current}'),
    (278, 28, 'geographic', 'Northern California', '#{time_current}', '#{time_current}'),
    (279, 28, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (280, 28, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (281, 28, 'internet', 'Broadband Internet', '#{time_current}', '#{time_current}'),
    (282, 28, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (283, 28, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (284, 28, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (285, 28, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (286, 28, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (287, 28, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (288, 28, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (289, 39, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (290, 39, 'ecosystem', 'Vernal Pools', '#{time_current}', '#{time_current}'),
    (291, 39, 'geographic', 'Central Valley', '#{time_current}', '#{time_current}'),
    (292, 39, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (293, 39, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (294, 39, 'facility', 'No Facilities', '#{time_current}', '#{time_current}'),
    (295, 39, 'internet', 'Cell Phone Only', '#{time_current}', '#{time_current}'),
    (296, 39, 'amenities', 'Vehicle', '#{time_current}', '#{time_current}'),
    (297, 19, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (298, 19, 'ecosystem', 'Coastal Sage Scrub', '#{time_current}', '#{time_current}'),
    (299, 19, 'ecosystem', 'Riparian', '#{time_current}', '#{time_current}'),
    (300, 19, 'geographic', 'Southern California', '#{time_current}', '#{time_current}'),
    (301, 19, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (302, 19, 'facility', 'Accommodate Less Than 30 Overnight', '#{time_current}', '#{time_current}'),
    (303, 19, 'internet', 'Broadband Internet, High Speed Internet', '#{time_current}', '#{time_current}'),
    (304, 19, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (305, 19, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (306, 19, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (307, 19, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (308, 19, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (309, 19, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (310, 502, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (311, 502, 'geographic', 'Desert', '#{time_current}', '#{time_current}'),
    (312, 502, 'geographic', 'Southern California', '#{time_current}', '#{time_current}'),
    (313, 502, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (314, 502, 'facility', 'No Facilities', '#{time_current}', '#{time_current}'),
    (315, 502, 'internet', 'Cell Phone Only', '#{time_current}', '#{time_current}'),
    (316, 502, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (317, 100008, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (318, 100008, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (319, 100008, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (320, 100008, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (321, 100008, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (322, 100008, 'geographic', 'Northern California', '#{time_current}', '#{time_current}'),
    (323, 100008, 'geographic', 'Coast Range', '#{time_current}', '#{time_current}'),
    (324, 100008, 'organization', 'Non Profit', '#{time_current}', '#{time_current}'),
    (325, 100008, 'facility', 'Accommodate Less Than 30 Overnight', '#{time_current}', '#{time_current}'),
    (326, 100008, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (327, 100008, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (328, 100008, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (329, 100008, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (330, 100008, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (331, 100008, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (332, 100008, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (333, 100008, 'amenities', 'Astronomical observatory', '#{time_current}', '#{time_current}'),
    (334, 100008, 'amenities', 'Herbarium', '#{time_current}', '#{time_current}'),
    (335, 27, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (336, 27, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (337, 27, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (338, 27, 'geographic', 'Northern California', '#{time_current}', '#{time_current}'),
    (339, 27, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (340, 27, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (341, 27, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (342, 27, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (343, 27, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (344, 27, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (345, 27, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (346, 27, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (347, 27, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (348, 34, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (349, 34, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (350, 34, 'ecosystem', 'Marsh', '#{time_current}', '#{time_current}'),
    (351, 34, 'ecosystem', 'Riparian', '#{time_current}', '#{time_current}'),
    (352, 34, 'ecosystem', 'River', '#{time_current}', '#{time_current}'),
    (353, 34, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (354, 34, 'geographic', 'Northern California', '#{time_current}', '#{time_current}'),
    (355, 34, 'geographic', 'Sierra Nevada', '#{time_current}', '#{time_current}'),
    (356, 34, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (357, 34, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (358, 34, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (359, 34, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (360, 34, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (361, 34, 'amenities', 'Vehicle', '#{time_current}', '#{time_current}'),
    (362, 34, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (363, 34, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (364, 34, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (365, 34, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (366, 34, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (367, 34, 'amenities', 'Library', '#{time_current}', '#{time_current}'),
    (368, 506, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (369, 506, 'ecosystem', 'Montane', '#{time_current}', '#{time_current}'),
    (370, 506, 'ecosystem', 'Redwoods', '#{time_current}', '#{time_current}'),
    (371, 506, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (372, 506, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (373, 506, 'organization', 'UC Other', '#{time_current}', '#{time_current}'),
    (374, 506, 'facility', 'Accommodate Less Than 30 Overnight', '#{time_current}', '#{time_current}'),
    (375, 506, 'internet', 'Satellite Internet', '#{time_current}', '#{time_current}'),
    (376, 506, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (377, 506, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (378, 506, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (379, 506, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (380, 17, 'ecosystem', 'Riparian', '#{time_current}', '#{time_current}'),
    (381, 17, 'ecosystem', 'Meadow', '#{time_current}', '#{time_current}'),
    (382, 17, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (383, 17, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (384, 17, 'geographic', 'Sierra Nevada', '#{time_current}', '#{time_current}'),
    (385, 17, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (386, 17, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (387, 17, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (388, 17, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (389, 17, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (390, 17, 'amenities', 'Boat', '#{time_current}', '#{time_current}'),
    (391, 17, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (392, 17, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (393, 17, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (394, 17, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (395, 17, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (396, 17, 'amenities', 'Animal care facilities', '#{time_current}', '#{time_current}'),
    (397, 17, 'amenities', 'Library', '#{time_current}', '#{time_current}'),
    (398, 17, 'amenities', 'Wet Laboratory', '#{time_current}', '#{time_current}'),
    (399, 17, 'amenities', 'Experimental Stream Channels', '#{time_current}', '#{time_current}'),
    (400, 23, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (401, 23, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (402, 23, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (403, 23, 'geographic', 'Northern California', '#{time_current}', '#{time_current}'),
    (404, 23, 'geographic', 'Coast Range', '#{time_current}', '#{time_current}'),
    (405, 23, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (406, 23, 'facility', 'No Facilities', '#{time_current}', '#{time_current}'),
    (407, 23, 'internet', 'No Network', '#{time_current}', '#{time_current}'),
    (408, 30, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (409, 30, 'ecosystem', 'Coastal Sage Scrub', '#{time_current}', '#{time_current}'),
    (410, 30, 'geographic', 'Coastal', '#{time_current}', '#{time_current}'),
    (411, 30, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (412, 30, 'geographic', 'Southern California', '#{time_current}', '#{time_current}'),
    (413, 30, 'organization', 'UC Other', '#{time_current}', '#{time_current}'),
    (414, 30, 'facility', 'Accommodate Less Than 30 Overnight', '#{time_current}', '#{time_current}'),
    (415, 30, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (416, 30, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (417, 30, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (418, 30, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (419, 30, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (420, 30, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (421, 30, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (422, 21, 'ecosystem', 'Chaparral', '#{time_current}', '#{time_current}'),
    (423, 21, 'ecosystem', 'Desert', '#{time_current}', '#{time_current}'),
    (424, 21, 'ecosystem', 'Oak Woodland', '#{time_current}', '#{time_current}'),
    (425, 21, 'ecosystem', 'Pinon-Juniper Woodland', '#{time_current}', '#{time_current}'),
    (426, 21, 'geographic', 'Desert', '#{time_current}', '#{time_current}'),
    (427, 21, 'geographic', 'Southern California', '#{time_current}', '#{time_current}'),
    (428, 21, 'geographic', 'Eastern California', '#{time_current}', '#{time_current}'),
    (429, 21, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (430, 21, 'facility', 'Accommodate Less Than 30 Overnight', '#{time_current}', '#{time_current}'),
    (431, 21, 'internet', 'Satellite Internet', '#{time_current}', '#{time_current}'),
    (432, 21, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (433, 21, 'amenities', 'Camping', '#{time_current}', '#{time_current}'),
    (434, 21, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (435, 21, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (436, 21, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (437, 21, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (438, 21, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (439, 21, 'amenities', 'Library', '#{time_current}', '#{time_current}'),
    (440, 21, 'amenities', 'Herbarium', '#{time_current}', '#{time_current}'),
    (441, 15, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (442, 15, 'ecosystem', 'Montane', '#{time_current}', '#{time_current}'),
    (443, 15, 'ecosystem', 'Riparian', '#{time_current}', '#{time_current}'),
    (444, 15, 'ecosystem', 'Meadow', '#{time_current}', '#{time_current}'),
    (445, 15, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (446, 15, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (447, 15, 'geographic', 'Sierra Nevada', '#{time_current}', '#{time_current}'),
    (448, 15, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (449, 15, 'facility', 'Accommodate Less Than 30 Overnight', '#{time_current}', '#{time_current}'),
    (450, 15, 'internet', 'Broadband Internet', '#{time_current}', '#{time_current}'),
    (451, 15, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (452, 15, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (453, 15, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (454, 15, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (455, 15, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (456, 38, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (457, 38, 'ecosystem', 'Desert', '#{time_current}', '#{time_current}'),
    (458, 38, 'ecosystem', 'Montane', '#{time_current}', '#{time_current}'),
    (459, 38, 'ecosystem', 'Alpine', '#{time_current}', '#{time_current}'),
    (460, 38, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (461, 38, 'geographic', 'Desert', '#{time_current}', '#{time_current}'),
    (462, 38, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (463, 38, 'geographic', 'Eastern California', '#{time_current}', '#{time_current}'),
    (464, 38, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (465, 38, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (466, 38, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (467, 38, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (468, 38, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (469, 38, 'amenities', 'Climate station', '#{time_current}', '#{time_current}'),
    (470, 38, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (471, 38, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (472, 38, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (473, 38, 'amenities', 'Animal care facilities', '#{time_current}', '#{time_current}'),
    (474, 38, 'amenities', 'Astronomical observatory', '#{time_current}', '#{time_current}'),
    (475, 36, 'ecosystem', 'Conifer Forest', '#{time_current}', '#{time_current}'),
    (476, 36, 'ecosystem', 'Montane', '#{time_current}', '#{time_current}'),
    (477, 36, 'ecosystem', 'Redwoods', '#{time_current}', '#{time_current}'),
    (478, 36, 'geographic', 'Mountains', '#{time_current}', '#{time_current}'),
    (479, 36, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (480, 36, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (481, 36, 'facility', 'Accommodate Over 30 Overnight', '#{time_current}', '#{time_current}'),
    (482, 36, 'internet', 'Broadband Internet', '#{time_current}', '#{time_current}'),
    (483, 36, 'amenities', 'Overnight housing', '#{time_current}', '#{time_current}'),
    (484, 36, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (485, 36, 'amenities', 'Classroom/Meeting space', '#{time_current}', '#{time_current}'),
    (486, 36, 'amenities', 'Laboratory', '#{time_current}', '#{time_current}'),
    (487, 36, 'amenities', 'Kitchen', '#{time_current}', '#{time_current}'),
    (488, 25, 'ecosystem', 'Costal Marine', '#{time_current}', '#{time_current}'),
    (489, 25, 'ecosystem', 'Grassland', '#{time_current}', '#{time_current}'),
    (490, 25, 'ecosystem', 'Marsh', '#{time_current}', '#{time_current}'),
    (491, 25, 'ecosystem', 'Coastal Sage Scrub', '#{time_current}', '#{time_current}'),
    (492, 25, 'ecosystem', 'Freshwater Wetland', '#{time_current}', '#{time_current}'),
    (493, 25, 'ecosystem', 'Riparian', '#{time_current}', '#{time_current}'),
    (494, 25, 'ecosystem', 'Lagoon', '#{time_current}', '#{time_current}'),
    (495, 25, 'geographic', 'Coastal', '#{time_current}', '#{time_current}'),
    (496, 25, 'geographic', 'Central California', '#{time_current}', '#{time_current}'),
    (497, 25, 'organization', 'UC NRS', '#{time_current}', '#{time_current}'),
    (498, 25, 'facility', 'No Facilities', '#{time_current}', '#{time_current}'),
    (499, 25, 'internet', 'High Speed Internet', '#{time_current}', '#{time_current}'),
    (500, 25, 'amenities', 'Internet', '#{time_current}', '#{time_current}'),
    (501, 25, 'amenities', 'Climate station', '#{time_current}', '#{time_current}');
    end_sql
  end
end
