require "rails_helper"

RSpec.describe ReserveForm, type: :model do
  describe "delegations" do
    it { is_expected.to delegate_method(:valid?).to(:reserve)}
    it { is_expected.to delegate_method(:validate).to(:reserve)}
    it { is_expected.to delegate_method(:errors).to(:reserve)}
    it { is_expected.to delegate_missing_methods_to(:reserve)}
  end

  describe "initializing" do
    it "makes an empty ReserveForm from empty params" do
      form = ReserveForm.new(params: {})

      expect(form).to have_attributes(
        id: nil,
        name: nil,
        short_name: nil,
        pulldown_name: "Pulldown",
        directions: nil,
        rules: nil,
        rates: nil,
        managing_campus_id: nil,
        department: nil,
        address_line_1: nil,
        address_line_2: nil,
        address_city: nil,
        address_postal_code: nil,
        billing_address_line_1: nil,
        billing_address_line_2: nil,
        billing_city: nil,
        billing_address_postal_code: nil,
        applicaton_email_address: nil,
        email_address: nil,
        phone_number: nil,
        fax_number: nil,
        check_payable_to_name: nil,
        home_page_url: nil,
        directions_url: nil,
        rules_url: nil,
        rates_url: "",
        research_projects_accepted: true,
        class_projects_accepted: true,
        public_projects_accepted: true,
        housing_projects_accepted: nil,
        conference_projects_accepted: false,
        public_calendar_access: false,
        how_to_contact: nil,
        approval_message: nil,
        email_message_2: nil,
        email_message_3: nil,
        email_message_4: nil,
        latitude: 0.0,
        longitude: 0.0,
        special_needs_statement: nil,
        invoice_message: nil,
        tax_id_number: nil,
        invoice_message_footer: nil,
        year_reserve_established: nil,
        show_rate_table: true,
        ldap_address: "uid=nrsadmin,o=unaffiliated,dc=ecoinformatics,dc=org",
        outside_reservation_system_url: "0",
        outside_reservation_system_text: nil,
        doi: "0",
        google_calendar_id: "0",
        reserve_alert_message_enabled: nil,
        reserve_alert_message: nil,
        code_of_conduct_url: "http://rams.ucnrs.org/PDF/nrs-codeofconduct.pdf",
        zotero_url: "https://www.zotero.org/groups/",
        zotero_login: nil,
        zotero_password: nil,
        facility_group_name: "No Facilities",
        internet_status: "Unknown",
        drop_box_login: "",
        drop_box_request_url: "https://www.dropbox.com/l/",
        amenity_group_label_1: "1",
        amenity_group_label_2: "2",
        amenity_group_label_3: "3",
        amenity_group_label_4: "4",
        amenity_group_label_5: "5",
        bill_name: nil,
        administrative_group_name: nil,
        administrative_group_name_acronym: nil,
        administrative_group_state: nil,
        address_state_id: nil,
        address_country_id: nil,
        billing_address_state_id: nil,
        billing_address_country_id: nil,
        latitude_degrees: nil,
        latitude_minutes: nil,
        latitude_seconds: nil,
        latitude_hemisphere: nil,
        longitude_degrees: nil,
        longitude_minutes: nil,
        longitude_seconds: nil,
        longitude_hemisphere: nil,
        description: nil,
        large_hero_photo_url: nil,
        listing_photo_url: nil,
      )
    end

    it "makes a new ReserveForm from params" do
      image = File.open(Rails.root.join('spec', 'support', 'assets', 'test-image.jpeg'))
      params = {
        id: 5,
        name: "reserve1",
        short_name: "res1",
        pulldown_name: "pulldown_name",
        directions: "directions",
        rules: "rules",
        rates: "rates",
        managing_campus_id: 5,
        department: "department",
        address_line_1: "address_line_1",
        address_line_2: "address_line_2",
        address_city: "address_city",
        address_postal_code: "postal_code",
        billing_address_line_1: "billing_address_line_1",
        billing_address_line_2: "billing_address_line_2",
        billing_city: "billing_city",
        billing_address_postal_code: "postal_code",
        applicaton_email_address: "applicaton_email_address",
        email_address: "email_address",
        phone_number: "phone_number",
        fax_number: "fax_number",
        check_payable_to_name: "check_payable_to_name",
        home_page_url: "home_page_url",
        directions_url: "directions_url",
        rules_url: "rules_url",
        rates_url: "rates_url",
        research_projects_accepted: false,
        class_projects_accepted: false,
        public_projects_accepted: false,
        housing_projects_accepted: false,
        conference_projects_accepted: true,
        public_calendar_access: false,
        how_to_contact: "how_to_contact",
        approval_message: "approval_message",
        email_message_2: "email_message_2",
        email_message_3: "email_message_3",
        email_message_4: "email_message_4",
        latitude: 10.0,
        longitude: 10.0,
        special_needs_statement: "special_needs_statement",
        invoice_message: "invoice_message",
        tax_id_number: "tax_id_number",
        invoice_message_footer: "invoice_message_footer",
        year_reserve_established: 1,
        show_rate_table: false,
        ldap_address: "ldap_address",
        outside_reservation_system_url: "outside_reservation_system_url",
        outside_reservation_system_text: "outside_reservation_system_text",
        doi: "doi",
        google_calendar_id: "google_calendar_id",
        reserve_alert_message_enabled: true,
        reserve_alert_message: "reserve_alert_message",
        code_of_conduct_url: "code_of_conduct_url",
        zotero_url: "zotero_url",
        zotero_login: "zotero_login",
        zotero_password: "zotero_password",
        facility_group_name: "No Facilities",
        internet_status: "High Speed Internet",
        drop_box_login: "drop_box_login",
        drop_box_request_url: "drop_box_request_url",
        amenity_group_label_1: "amenity_group_label_1",
        amenity_group_label_2: "amenity_group_label_2",
        amenity_group_label_3: "amenity_group_label_3",
        amenity_group_label_4: "amenity_group_label_4",
        amenity_group_label_5: "amenity_group_label_5",
        bill_name: "bill_name",
        administrative_group_name: "administrative_group_name",
        administrative_group_name_acronym: "administrative_group_name_acronym",
        administrative_group_state: "administrative_group_state",
        address_state_id: 4,
        address_country_id: 4,
        billing_address_state_id: 4,
        billing_address_country_id: 4,
        latitude_degrees: 1.0,
        latitude_minutes: 1.0,
        latitude_seconds: 1.0,
        latitude_hemisphere: "latitude_hemisphere",
        longitude_degrees: 1.0,
        longitude_minutes: 1.0,
        longitude_seconds: 1.0,
        longitude_hemisphere: "longitude_hemisphere",
        description: "description",
        logo: image,
        listing_photo: image,
        large_hero_photo: image,
      }
      form = ReserveForm.new(params: params)

      expect(form).to have_attributes(
        id: 5,
        name: "reserve1",
        short_name: "res1",
        pulldown_name: "pulldown_name",
        directions: "directions",
        rules: "rules",
        rates: "rates",
        managing_campus_id: 5,
        department: "department",
        address_line_1: "address_line_1",
        address_line_2: "address_line_2",
        address_city: "address_city",
        address_postal_code: "postal_code",
        billing_address_line_1: "billing_address_line_1",
        billing_address_line_2: "billing_address_line_2",
        billing_city: "billing_city",
        billing_address_postal_code: "postal_code",
        applicaton_email_address: "applicaton_email_address",
        email_address: "email_address",
        phone_number: "phone_number",
        fax_number: "fax_number",
        check_payable_to_name: "check_payable_to_name",
        home_page_url: "home_page_url",
        directions_url: "directions_url",
        rules_url: "rules_url",
        rates_url: "rates_url",
        research_projects_accepted: false,
        class_projects_accepted: false,
        public_projects_accepted: false,
        housing_projects_accepted: false,
        conference_projects_accepted: true,
        public_calendar_access: false,
        how_to_contact: "how_to_contact",
        approval_message: "approval_message",
        email_message_2: "email_message_2",
        email_message_3: "email_message_3",
        email_message_4: "email_message_4",
        latitude: 10.0,
        longitude: 10.0,
        special_needs_statement: "special_needs_statement",
        invoice_message: "invoice_message",
        tax_id_number: "tax_id_number",
        invoice_message_footer: "invoice_message_footer",
        year_reserve_established: 1,
        show_rate_table: false,
        ldap_address: "ldap_address",
        outside_reservation_system_url: "outside_reservation_system_url",
        outside_reservation_system_text: "outside_reservation_system_text",
        doi: "doi",
        google_calendar_id: "google_calendar_id",
        reserve_alert_message_enabled: true,
        reserve_alert_message: "reserve_alert_message",
        code_of_conduct_url: "code_of_conduct_url",
        zotero_url: "zotero_url",
        zotero_login: "zotero_login",
        zotero_password: "zotero_password",
        facility_group_name: "No Facilities",
        internet_status: "High Speed Internet",
        drop_box_login: "drop_box_login",
        drop_box_request_url: "drop_box_request_url",
        amenity_group_label_1: "amenity_group_label_1",
        amenity_group_label_2: "amenity_group_label_2",
        amenity_group_label_3: "amenity_group_label_3",
        amenity_group_label_4: "amenity_group_label_4",
        amenity_group_label_5: "amenity_group_label_5",
        bill_name: "bill_name",
        administrative_group_name: "administrative_group_name",
        administrative_group_name_acronym: "administrative_group_name_acronym",
        administrative_group_state: "administrative_group_state",
        address_state_id: 4,
        address_country_id: 4,
        billing_address_state_id: 4,
        billing_address_country_id: 4,
        latitude_degrees: 1.0,
        latitude_minutes: 1.0,
        latitude_seconds: 1.0,
        latitude_hemisphere: "latitude_hemisphere",
        longitude_degrees: 1.0,
        longitude_minutes: 1.0,
        longitude_seconds: 1.0,
        longitude_hemisphere: "longitude_hemisphere",
        description: "description",
        logo_url: a_string_matching(/\/tmp\/ucnrs-test\/cache\/reserve_id_5\/\S+\/test-image.jpeg/),
        large_hero_photo_url: a_string_matching(/\/tmp\/ucnrs-test\/cache\/reserve_id_5\/\S+\/test-image.jpeg/),
        listing_photo_url: a_string_matching(/\/tmp\/ucnrs-test\/cache\/reserve_id_5\/\S+\/test-image.jpeg/),
      )
    end
  end

  describe "#save" do
    it "update the given reserve if there are no errors" do
      image = File.open(Rails.root.join('spec', 'support', 'assets', 'test-image.jpeg'))
      reserve = create(:reserve)
      country = create(:country)
      state = create(:state, country: country)
      form = ReserveForm.new(reserve: reserve, params: {
        name: "reserve1",
        short_name: "res1",
        pulldown_name: "pulldown_name",
        directions: "directions",
        rules: "rules",
        rates: "rates",
        managing_campus_id: 5,
        department: "department",
        address_line_1: "address_line_1",
        address_line_2: "address_line_2",
        address_city: "address_city",
        address_postal_code: "postal_code",
        billing_address_line_1: "billing_address_line_1",
        billing_address_line_2: "billing_address_line_2",
        billing_city: "billing_city",
        billing_address_postal_code: "postal_code",
        applicaton_email_address: "applicaton_email_address",
        email_address: "email_address",
        phone_number: "phone_number",
        fax_number: "fax_number",
        check_payable_to_name: "check_payable_to_name",
        home_page_url: "home_page_url",
        directions_url: "directions_url",
        rules_url: "rules_url",
        rates_url: "rates_url",
        research_projects_accepted: false,
        class_projects_accepted: false,
        public_projects_accepted: false,
        housing_projects_accepted: false,
        conference_projects_accepted: true,
        public_calendar_access: false,
        how_to_contact: "how_to_contact",
        approval_message: "approval_message",
        email_message_2: "email_message_2",
        email_message_3: "email_message_3",
        email_message_4: "email_message_4",
        latitude: 10.0,
        longitude: 10.0,
        special_needs_statement: "special_needs_statement",
        invoice_message: "invoice_message",
        tax_id_number: "tax_id_number",
        invoice_message_footer: "footer",
        year_reserve_established: 1,
        show_rate_table: false,
        ldap_address: "ldap_address",
        outside_reservation_system_url: "outside_reservation_system_url",
        outside_reservation_system_text: "outside_reservation_system_text",
        doi: "doi",
        google_calendar_id: "google_calendar_id",
        reserve_alert_message_enabled: true,
        reserve_alert_message: "reserve_alert_message",
        code_of_conduct_url: "code_of_conduct_url",
        zotero_url: "zotero_url",
        zotero_login: "zotero_login",
        zotero_password: "zotero_password",
        facility_group_name: "No Facilities",
        internet_status: "High Speed Internet",
        drop_box_login: "drop_box_login",
        drop_box_request_url: "drop_box_request_url",
        amenity_group_label_1: "amenity_group_label_1",
        amenity_group_label_2: "amenity_group_label_2",
        amenity_group_label_3: "amenity_group_label_3",
        amenity_group_label_4: "amenity_group_label_4",
        amenity_group_label_5: "amenity_group_label_5",
        bill_name: "bill_name",
        administrative_group_name: "administrative_group_name",
        administrative_group_name_acronym: "administrative_group_name_acronym",
        administrative_group_state: "administrative_group_state",
        address_state_id: state.id,
        address_country_id: country.id,
        billing_address_state_id: 4,
        billing_address_country_id: 4,
        description: "description",
        logo: image,
        listing_photo: image,
        large_hero_photo: image,
      })

      result = form.save

      expect(result).to be_truthy
      expect(form.reserve).to be_persisted
      expect(form.reserve).to have_attributes(
        id: reserve.id,
        name: "reserve1",
        short_name: "res1",
        pulldown_name: "pulldown_name",
        directions: "directions",
        rules: "rules",
        rates: "rates",
        managing_campus_id: 5,
        department: "department",
        address_line_1: "address_line_1",
        address_line_2: "address_line_2",
        address_city: "address_city",
        address_postal_code: "postal_code",
        billing_address_line_1: "billing_address_line_1",
        billing_address_line_2: "billing_address_line_2",
        billing_city: "billing_city",
        billing_address_postal_code: "postal_code",
        applicaton_email_address: "applicaton_email_address",
        email_address: "email_address",
        phone_number: "phone_number",
        fax_number: "fax_number",
        check_payable_to_name: "check_payable_to_name",
        home_page_url: "home_page_url",
        directions_url: "directions_url",
        rules_url: "rules_url",
        rates_url: "rates_url",
        research_projects_accepted: false,
        class_projects_accepted: false,
        public_projects_accepted: false,
        housing_projects_accepted: false,
        conference_projects_accepted: true,
        public_calendar_access: false,
        how_to_contact: "how_to_contact",
        approval_message: "approval_message",
        email_message_2: "email_message_2",
        email_message_3: "email_message_3",
        email_message_4: "email_message_4",
        latitude: 10.0,
        longitude: 10.0,
        special_needs_statement: "special_needs_statement",
        invoice_message: "invoice_message",
        tax_id_number: "tax_id_number",
        invoice_message_footer: "footer",
        year_reserve_established: 1,
        show_rate_table: false,
        ldap_address: "ldap_address",
        outside_reservation_system_url: "outside_reservation_system_url",
        outside_reservation_system_text: "outside_reservation_system_text",
        doi: "doi",
        google_calendar_id: "google_calendar_id",
        reserve_alert_message_enabled: true,
        reserve_alert_message: "reserve_alert_message",
        code_of_conduct_url: "code_of_conduct_url",
        zotero_url: "zotero_url",
        zotero_login: "zotero_login",
        zotero_password: "zotero_password",
        facility_group_name: "No Facilities",
        internet_status: "High Speed Internet",
        drop_box_login: "drop_box_login",
        drop_box_request_url: "drop_box_request_url",
        amenity_group_label_1: "amenity_group_label_1",
        amenity_group_label_2: "amenity_group_label_2",
        amenity_group_label_3: "amenity_group_label_3",
        amenity_group_label_4: "amenity_group_label_4",
        amenity_group_label_5: "amenity_group_label_5",
        bill_name: "bill_name",
        administrative_group_name: "administrative_group_name",
        administrative_group_name_acronym: "administrative_group_name_acronym",
        administrative_group_state: "administrative_group_state",
        address_state_id: state.id,
        address_country_id: country.id,
        billing_address_state_id: 4,
        billing_address_country_id: 4,
        description: "description",
        logo_url: a_string_matching(/\/tmp\/ucnrs-test\/reserve_id_#{reserve.id}\/test-image.jpeg/),
        listing_photo_url: a_string_matching(/\/tmp\/ucnrs-test\/reserve_id_#{reserve.id}\/test-image.jpeg/),
        large_hero_photo_url: a_string_matching(/\/tmp\/ucnrs-test\/reserve_id_#{reserve.id}\/test-image.jpeg/),
      )
    end

    it "creates new reserve if there are no errors" do
      image = File.open(Rails.root.join('spec', 'support', 'assets', 'test-image.jpeg'))
      country = create(:country)
      state = create(:state, country: country)
      form = ReserveForm.new(params: {
        name: "reserve1",
        short_name: "res1",
        pulldown_name: "pulldown_name",
        directions: "directions",
        rules: "rules",
        rates: "rates",
        managing_campus_id: 5,
        department: "department",
        address_line_1: "address_line_1",
        address_line_2: "address_line_2",
        address_city: "address_city",
        address_postal_code: "postal_code",
        billing_address_line_1: "billing_address_line_1",
        billing_address_line_2: "billing_address_line_2",
        billing_city: "billing_city",
        billing_address_postal_code: "postal_code",
        applicaton_email_address: "applicaton_email_address",
        email_address: "email_address",
        phone_number: "phone_number",
        fax_number: "fax_number",
        check_payable_to_name: "check_payable_to_name",
        home_page_url: "home_page_url",
        directions_url: "directions_url",
        rules_url: "rules_url",
        rates_url: "rates_url",
        research_projects_accepted: false,
        class_projects_accepted: false,
        public_projects_accepted: false,
        housing_projects_accepted: false,
        conference_projects_accepted: true,
        public_calendar_access: false,
        how_to_contact: "how_to_contact",
        approval_message: "approval_message",
        email_message_2: "email_message_2",
        email_message_3: "email_message_3",
        email_message_4: "email_message_4",
        latitude: 10.0,
        longitude: 10.0,
        special_needs_statement: "special_needs_statement",
        invoice_message: "invoice_message",
        tax_id_number: "tax_id_number",
        invoice_message_footer: "footer",
        year_reserve_established: 1,
        show_rate_table: false,
        ldap_address: "ldap_address",
        outside_reservation_system_url: "outside_reservation_system_url",
        outside_reservation_system_text: "outside_reservation_system_text",
        doi: "doi",
        google_calendar_id: "google_calendar_id",
        reserve_alert_message_enabled: true,
        reserve_alert_message: "reserve_alert_message",
        code_of_conduct_url: "code_of_conduct_url",
        zotero_url: "zotero_url",
        zotero_login: "zotero_login",
        zotero_password: "zotero_password",
        facility_group_name: "No Facilities",
        internet_status: "High Speed Internet",
        drop_box_login: "drop_box_login",
        drop_box_request_url: "drop_box_request_url",
        amenity_group_label_1: "amenity_group_label_1",
        amenity_group_label_2: "amenity_group_label_2",
        amenity_group_label_3: "amenity_group_label_3",
        amenity_group_label_4: "amenity_group_label_4",
        amenity_group_label_5: "amenity_group_label_5",
        bill_name: "bill_name",
        administrative_group_name: "administrative_group_name",
        administrative_group_name_acronym: "administrative_group_name_acronym",
        administrative_group_state: "administrative_group_state",
        address_state_id: state.id,
        address_country_id: country.id,
        billing_address_state_id: 4,
        billing_address_country_id: 4,
        description: "description",
        logo: image,
        listing_photo: image,
        large_hero_photo: image,
      })

      result = form.save

      expect(result).to be_truthy
      expect(form.reserve).to be_persisted
      expect(form.reserve).to have_attributes(
        name: "reserve1",
        short_name: "res1",
        pulldown_name: "pulldown_name",
        directions: "directions",
        rules: "rules",
        rates: "rates",
        managing_campus_id: 5,
        department: "department",
        address_line_1: "address_line_1",
        address_line_2: "address_line_2",
        address_city: "address_city",
        address_postal_code: "postal_code",
        billing_address_line_1: "billing_address_line_1",
        billing_address_line_2: "billing_address_line_2",
        billing_city: "billing_city",
        billing_address_postal_code: "postal_code",
        applicaton_email_address: "applicaton_email_address",
        email_address: "email_address",
        phone_number: "phone_number",
        fax_number: "fax_number",
        check_payable_to_name: "check_payable_to_name",
        home_page_url: "home_page_url",
        directions_url: "directions_url",
        rules_url: "rules_url",
        rates_url: "rates_url",
        research_projects_accepted: false,
        class_projects_accepted: false,
        public_projects_accepted: false,
        housing_projects_accepted: false,
        conference_projects_accepted: true,
        public_calendar_access: false,
        how_to_contact: "how_to_contact",
        approval_message: "approval_message",
        email_message_2: "email_message_2",
        email_message_3: "email_message_3",
        email_message_4: "email_message_4",
        latitude: 10.0,
        longitude: 10.0,
        special_needs_statement: "special_needs_statement",
        invoice_message: "invoice_message",
        tax_id_number: "tax_id_number",
        invoice_message_footer: "footer",
        year_reserve_established: 1,
        show_rate_table: false,
        ldap_address: "ldap_address",
        outside_reservation_system_url: "outside_reservation_system_url",
        outside_reservation_system_text: "outside_reservation_system_text",
        doi: "doi",
        google_calendar_id: "google_calendar_id",
        reserve_alert_message_enabled: true,
        reserve_alert_message: "reserve_alert_message",
        code_of_conduct_url: "code_of_conduct_url",
        zotero_url: "zotero_url",
        zotero_login: "zotero_login",
        zotero_password: "zotero_password",
        facility_group_name: "No Facilities",
        internet_status: "High Speed Internet",
        drop_box_login: "drop_box_login",
        drop_box_request_url: "drop_box_request_url",
        amenity_group_label_1: "amenity_group_label_1",
        amenity_group_label_2: "amenity_group_label_2",
        amenity_group_label_3: "amenity_group_label_3",
        amenity_group_label_4: "amenity_group_label_4",
        amenity_group_label_5: "amenity_group_label_5",
        bill_name: "bill_name",
        administrative_group_name: "administrative_group_name",
        administrative_group_name_acronym: "administrative_group_name_acronym",
        administrative_group_state: "administrative_group_state",
        address_state_id: state.id,
        address_country_id: country.id,
        billing_address_state_id: 4,
        billing_address_country_id: 4,
        description: "description",
        logo_url: a_string_matching(/\/tmp\/ucnrs-test\/reserve_id_#{form.reserve.id}\/test-image.jpeg/),
        listing_photo_url: a_string_matching(/\/tmp\/ucnrs-test\/reserve_id_#{form.reserve.id}\/test-image.jpeg/),
        large_hero_photo_url: a_string_matching(/\/tmp\/ucnrs-test\/reserve_id_#{form.reserve.id}\/test-image.jpeg/),
      )
    end

    it "makes sure errors are visible when save fails" do
      form = ReserveForm.new(params: {})

      result = form.save

      expect(result).to be_falsy
      expect(form.reserve).to_not be_persisted
      expect(form.errors).to be_present
    end
  end
end
